# This file is intended for development use only, to start the required backend

version: '3.5'
services:
  db:
    image: mongo:latest
    container_name: db
    environment:
      MONGO_INITDB_DATABASE: uad
    ports:
      - "27017:27017"
    networks:
      - dev

networks:
  dev:
    name: dev
    external: true